### PR TITLE
[bug 1267266] Rename locale dirs with dashes to use underscores.

### PR DESCRIPTION
**Pull request by Osmose**
@mathjazz @flodolo r?

I found while investigated [bug 1267266](https://bugzilla.mozilla.org/show_bug.cgi?id=1267266) that Input doesn't load translations from locale directories that use a `-` in them instead of a `_`. This change renames all the directories that still have `-` in them.

Pontoon should be able to handle this fine, it looks for both variants when locating resource files. I'm not sure if other tooling we have will break, hence the PR and request for review. Thanks!

### CODE REVIEW

**Comment by flodolo** [comment]
Webstatus is the only other tool involved and should be OK with _, but I'm pretty sure Matjaz needs to manually fix stuff in the DB to maintain attributions.

**Comment by mathjazz** [comment]
This should just work in Pontoon.

r+

**Comment by Osmose** [comment]
Thanks, seems to have worked fine on the Input side of things. :D

**Comment by mathjazz** [comment]
Pontoon also synced and everything seems fine.

**Pull request merged**
